name: Testing

on: push

jobs:
  test:
    name: Tests passes
    runs-on: ubuntu-latest

    steps:
      - name: ⬇ Git checkout
        uses: actions/checkout@v3

      - name: 💾 Install modules
        run: npm ci

      - name: 🧪 Testing
        run: npm test
        env:
          REACT_APP_HACKANDEAT_URL: ${{ https://api.edamam.com/api/recipes/v2 }}
          REACT_APP_API_PARAMS: ${{ field=label&field=image&imageSize=REGULAR&field=foodId&field=dishType&field=calories&field=cuisineType&field=totalNutrients&app_id=3ecd7851&type=public }}
          REACT_APP_API_KEY: ${{ 498953c8163cbec03246cd4914d809ec }}
